// <auto-generated />
namespace ACMA.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ALTER_COLUM_IPADDRESS_MAXLENGHT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTER_COLUM_IPADDRESS_MAXLENGHT));
        
        string IMigrationMetadata.Id
        {
            get { return "201512231737015_ALTER_COLUM_IPADDRESS_MAXLENGHT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
